FinTech/Controllers/BalanceController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using FinTech.Models;
using FinTech.Services.BalanceServices;
using FinTech.Services.CompanyService;
using FinTech.Services.ExcellReportsService;
using FinTech.Services.FileService;
using FinTech.ViewModels.Balances;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace FinTech.Controllers
{
    [Authorize]
    public class BalanceController : Controller
    {
        private readonly IBalanceService _balanceService;
        private readonly ICompanyService _companyService;
        private readonly UserManager<User> _userManager;
        private readonly ExcelReports _excelReports;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _hostEnvironment;
        private static readonly Logger Logger = LogManager.GetLogger("BalanceLogger");


        public BalanceController(IBalanceService balanceService, ICompanyService companyService, UserManager<User> userManager, ExcelReports excelReports, IFileService fileService, IWebHostEnvironment hostEnvironment)
        {
            _balanceService = balanceService;
            _companyService = companyService;
            _userManager = userManager;
            _excelReports = excelReports;
            _fileService = fileService;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(int year)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var company = _companyService.GetCompanyFromUser(user);
                BalanceReportViewModel model = _balanceService.BuildBalanceReportByYear(year, company);
                ModelState.Clear();
                return View(model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Index\n {e}");
                throw;
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> GetExcelReport(BalanceReportViewModel viewModel)
        {
            try
            {
                Logger.Info($"Входные данные GetExcelReport: \n {viewModel}");
                var user = await _userManager.GetUserAsync(User);
                var company = _companyService.GetCompanyFromUser(user);
                var model = _balanceService.BuildBalanceReportByYear(viewModel.YearOfReport.Year, company);
                var fileName = _excelReports.BalanceReport(model);
                var filePath = Path.Combine(_hostEnvironment.ContentRootPath, "VirtualFiles", fileName);
                string fileType = "application/xlsx";
                return _fileService.GetFileStream(filePath, fileType, fileName);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetExcelReport\n {e}");
                throw;
            }
        }
    }
}

FinTech/Controllers/BudgetItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinTech.Enums;
using FinTech.Models;
using FinTech.Services.AssetLiabilityService;
using FinTech.Services.BudgetItemService;
using FinTech.ViewModels.AssetLiabilities;
using FinTech.ViewModels.BudgetItems;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace FinTech.Controllers
{
    [Authorize]
    public class BudgetItemController : Controller
    {
        private readonly IBudgetItemService _budgetItemService;
        private readonly IMapper _mapper;
        private readonly IAssetLiabilityService _assetLiabilityService;
        private readonly UserManager<User> _userManager;
        private static readonly Logger Logger = LogManager.GetLogger("BudgetItemLogger");

        public BudgetItemController(
            IBudgetItemService budgetItemService, 
            IMapper mapper, 
            IAssetLiabilityService assetLiabilityService,
            UserManager<User> userManager)
        {
            _budgetItemService = budgetItemService;
            _mapper = mapper;
            _userManager = userManager;
            _assetLiabilityService = assetLiabilityService;
        }

        [HttpGet]
        public IActionResult CreateBudgetItem()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetFormBudgetItem(string budgetType)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var companyId = user.Company.Id;
                var assets = _assetLiabilityService.GetAssetLiabilitiesByCompanyIdAndType(companyId, AssetLiabilityTypes.Asset);
                var liabilities = _assetLiabilityService.GetAssetLiabilitiesByCompanyIdAndType(companyId, AssetLiabilityTypes.Liability);
                CreateBudgetItemViewModel model = new CreateBudgetItemViewModel()
                {
                    Assets = _mapper.Map<List<AssetLiabilityViewModel>>(assets.ToList()),
                    Liabilities = _mapper.Map<List<AssetLiabilityViewModel>>(liabilities.ToList()),
                    CompanyBin = user.Company.Bin
                };
                Logger.Info($"Входные данные GetFormBudgetItem\n {model}");
                if (budgetType == "Income")
                    return PartialView("~/Views/PartialViews/BudgetItem/_BudgetItemIncome.cshtml", model);
                if (budgetType == "Expense")
                    return PartialView("~/Views/PartialViews/BudgetItem/_BudgetItemExpense.cshtml", model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetFormBudgetItem:\n {e}");
                return BadRequest(400);
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult CreateBudgetItem(CreateBudgetItemViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные GetFormBudgetItem\n {model}");
                if (ModelState.IsValid)
                    _budgetItemService.CreateBudgetItem(model);
                ModelState.Clear();
                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CreateBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult EditBudgetItem(string id)
        {
            try
            {
                if (_budgetItemService.CheckExistById(id))
                {
                    var budgetItem = _budgetItemService.GetBudgetItemById(id);
                    var model = _mapper.Map<BudgetItemViewModel>(budgetItem);
                    return View(model);
                }
                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CreateBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpPost]
        [Authorize(Roles = "root, admin")]
        public async Task<IActionResult> EditBudgetItem(UpdateBudgetItemViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные в методе EditBudgetItem:\n {model}");
                if (_budgetItemService.CheckExistById(model.Id))
                {
                    var user = await _userManager.GetUserAsync(User);
                    model.CompanyId = user.Company.Id;
                    _budgetItemService.UpdateBudgetItem(model);
                    return RedirectToAction("GetBudgetIemList");
                }
                ModelState.Clear();
                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе EditBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult DeleteBudgetItem(string id)
        {
            try
            {
                if (_budgetItemService.CheckExistById(id))
                {
                    _budgetItemService.DeleteBudgetItemById(id);
                    return RedirectToAction("GetBudgetIemList"); 
                }

                return NotFound();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе DeleteBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetBudgetIemList()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var testCompanyId = user.Company.Id;
                var budgetItems = _budgetItemService.GetBudgetItemsListByCompanyId(testCompanyId, null);
                var budgetItemsList = _mapper.Map<List<BudgetItemViewModel>>(budgetItems.ToList());
                return View(budgetItemsList);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetBudgetIemList:\n {e}");
                return BadRequest(400);
            }
        }
    }
}

FinTech/Controllers/CashFlowController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using FinTech.Models;
using FinTech.Services.CashFlowService;
using FinTech.Services.ExcellReportsService;
using FinTech.Services.FileService;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace FinTech.Controllers
{
    public class CashFlowController : Controller
    {
        private readonly ICashFlowService _cashFlowService;
        private readonly UserManager<User> _userManager;
        private static readonly Logger Logger = LogManager.GetLogger("CashFlowLogger");
        private readonly ExcelReports _excelReports;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _hostEnvironment;
        
        public CashFlowController(ICashFlowService cashFlowService,
            UserManager<User> userManager, ExcelReports excelReports, IFileService fileService, IWebHostEnvironment hostEnvironment)
        {
            _cashFlowService = cashFlowService;
            _userManager = userManager;
            _excelReports = excelReports;
            _fileService = fileService;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult CashFlowReport()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CashFlowReport(int year)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var model = _cashFlowService.BuildCashFlowReportByYear(year, user.Company.Id);
                return View(model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CashFlowReport\n {e}");
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> GetExcelReport(int year)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var model = _cashFlowService.BuildCashFlowReportByYear(year, user.Company.Id);
                var fileName = _excelReports.CashFlowReport(model);
                var filePath = Path.Combine(_hostEnvironment.ContentRootPath, "VirtualFiles", fileName);
                string fileType = "application/xlsx";
                return _fileService.GetFileStream(filePath, fileType, fileName);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetExcelReport\n {e}");
                throw;
            }
        }
    }
}

FinTech/Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using FinTech.Enums;
using FinTech.Models;
using FinTech.Services.Charts;
using FinTech.ViewModels.BudgetItems;
using FinTech.ViewModels.Charts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NLog;

namespace FinTech.Controllers
{
    public class ChartsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IChartsService _chartsService;
        private static readonly Logger Logger = LogManager.GetLogger("ChartsLogger");

        public ChartsController(
            UserManager<User> userManager, 
            IChartsService chartsService
            )
        {
            _userManager = userManager;
            _chartsService = chartsService;
        }
        
        public IActionResult Index()
        {
            try
            {
                if (User.Identity.Name is null)
                    return RedirectToAction("Login","Account");
                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Index:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public async Task<string> ReturnBudgetItemViewModels(int year, int budgetItemType)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var currentCompany = user.Company;
                List<ChartsBudgetItemViewModel> returnCollection = new List<ChartsBudgetItemViewModel>();
                if (budgetItemType == 1)
                    returnCollection = _chartsService.ReturnBudgetItems(
                        year, 
                        currentCompany.Id,
                        BudgetItemTypes.Income);
                else
                    returnCollection = _chartsService.ReturnBudgetItems(
                        year, 
                        currentCompany.Id,
                        BudgetItemTypes.Expense);
                return JsonConvert.SerializeObject(returnCollection);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ReturnBudgetItemViewModels:\n {e}");
                return null;
            }
        }
        
        [HttpGet]
        public async Task<string> ReturnCounterpartyViewModels(int year)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var currentCompany = user.Company;
                var returnCollection = _chartsService
                    .ReturnIncomeCounterparties(year, currentCompany.Id);
                return JsonConvert.SerializeObject(returnCollection);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ReturnCounterpartyViewModels:\n {e}");
                return null;
            }
        }

        [HttpGet]
        public async Task<string> ReturnPnlReport(int year)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var currentCompany = user.Company;
                var returnModel = _chartsService
                    .ReturnReport(ReportTypes.PnL, year, OperationTypes.Operational, currentCompany.Id);
                return JsonConvert.SerializeObject(returnModel);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ReturnPnlReport:\n {e}");
                return null;
            }
        }
        
        [HttpGet]
        public async Task<string> ReturnCashFlowReport(int year, OperationTypes type)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var currentCompany = user.Company;
                var returnModel = _chartsService
                    .ReturnReport(ReportTypes.CashFlow, year, type, currentCompany.Id);
                return JsonConvert.SerializeObject(returnModel);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ReturnCashFlowReport:\n {e}");
                return null;
            }
        }

        [HttpGet]
        public PartialViewResult ReturnReportInfoPartialView(string viewModel)
        {
            try
            {
                var model = JsonConvert.DeserializeObject<ChartsReportViewModel>(viewModel);
                if (model != null)
                {
                    if (model.Profitability != null)
                        return PartialView("~/Views/PartialViews/Charts/_PnlChartInfo.cshtml", model);
                    return PartialView("~/Views/PartialViews/Charts/_CashflowChartInfo.cshtml", model);
                }
                return null;
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ReturnReportInfoPartialView:\n {e}");
                return null;
            }
        }
    }
}

FinTech/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] FinTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/dimensions.css" asp-append-version="true"/>
</head>
<body>

@RenderBody()

</body>
</html>

FinTech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100 w-100">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] FinTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/dimensions.css" asp-append-version="true"/>
</head>
<body class="h-100 w-100">
<div class="justify-content-start w-100 position-relative relative-height">
    <div class="justify-content-start relative-height">
        <header class="position-relative">
            <div class="layout-header-vertical relative-height">
                <div class="w-auto d-block navbar-logo-container img-fluid">
                    <img class="navbar-logo" src="~/images/logo.jpg" alt="">
                </div>
                <div class="navbar-items">
                    <a asp-action="Index" asp-controller="Charts" class="navbar-item-link disabled-link color-white">
                        <div class="navbar-item-container">
                            <div class="w-100 justify-content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-graph-up navbar-item" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M0 0h1v15h15v1H0V0zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5z"/>
                                </svg>
                            </div>
                            <div class="justify-content-center">
                                <p class="main-icon-text">Показатели</p>
                            </div>
                        </div>
                    </a>
                    <a asp-action="Index" asp-controller="Operation" class="navbar-item-link disabled-link color-white">
                        <div class="navbar-item-container">
                            <div class="w-100 justify-content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-repeat navbar-item" viewBox="0 0 16 16">
                                    <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
                                    <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
                                </svg>
                            </div>
                            <div class="justify-content-center">
                                <p class="main-icon-text">Операции</p>
                            </div>
                        </div>
                    </a>
                    <div class="btn-group dropright navbar-item-link disabled-link color-white">
                        <div class="navbar-item-container position-relative report-dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="w-100 justify-content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-archive navbar-item" viewBox="0 0 16 16">
                                    <path d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                                </svg>
                            </div>
                            <div class="justify-content-center">
                                <button class="disabled-button color-white">
                                    <p class="main-icon-text">Настройки</p>
                                </button>
                            </div>
                        </div>
                        <div class="dropdown-menu reports-dropdown-menu">
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="Index" asp-controller="Company">
                                    <b class="report-dropdown-item-text">Компания</b>
                                </a>
                            </div>
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="Index" asp-controller="Counterparty">
                                    <b class="report-dropdown-item-text">Контрагенты</b>
                                </a>
                            </div>
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="Index" asp-controller="PaymentAccount">
                                    <b class="report-dropdown-item-text">Платежные счета</b>
                                </a>
                            </div>
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="CreateBudgetItem" asp-controller="BudgetItem">
                                    <b class="report-dropdown-item-text">Учетные статьи</b>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="btn-group dropright navbar-item-link disabled-link color-white">
                        <div class="navbar-item-container position-relative report-dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="w-100 justify-content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-file-earmark-text navbar-item" viewBox="0 0 16 16">
                                    <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                                    <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                                </svg>
                            </div>
                            <div class="justify-content-center">
                                <button class="disabled-button color-white">
                                    <p class="main-icon-text">Отчеты</p>
                                </button>
                            </div>
                        </div>
                        <div class="dropdown-menu reports-dropdown-menu">
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="ProfitAndLosesReport" asp-controller="ProfitAndLoses">
                                    <b class="report-dropdown-item-text">PnL</b>
                                </a>
                            </div>
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="CashFlowReport" asp-controller="CashFlow">
                                    <b class="report-dropdown-item-text">Cashflow</b>
                                </a>
                            </div>
                            <div class="report-dropdown-item">
                                <a class="disabled-link" asp-action="Index" asp-controller="Balance">
                                    <b class="report-dropdown-item-text">Баланс</b>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <div class="w-100">
        <header class="justify-content-between">
            <div class="w-100 justify-content-start">
                <div class="w-100 layout-header-horizontal justify-content-between">
                    <div class="w-75"></div>
                    <div class="justify-content-start">
                        <div class="balance d-block w-auto" url="@Url.Action("GetCompanyPaymentAccounts", "PaymentAccount")">
                            <ul class="navbar-nav balances flex-grow-1"></ul>
                        </div>
                        <div class="ml-3">
                            <form asp-action="Logout" asp-controller="Account" method="post" asp-antiforgery="true">
                                <button type="submit" class="btn btn-danger">Выйти</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="position-relative main-container w-100">
            <div class="body-container">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

@*<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - ESDP_csharp5 -
    </div>
</footer>*@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
<script src="~/lib/chart/js/chart.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/load_payment_account_block.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>