FinTech/Models/PaymentAccount.cs
using System;
using FinTech.Enums;

namespace FinTech.Models
{
    public class PaymentAccount
    {
        public string Id { get; set; }
        public string Iban { get; set; }
        public decimal Amount { get; set; }
        public CurrencyTypes CurrencyType { get; set; }
        public DateTime CreationDate { get; set; }
        public string CompanyId { get; set; }
        public virtual Company? Company { get; set; }
        public string CounterpartyId { get; set; }
        public virtual Counterparty? Counterparty { get; set; }
        public string BankId { get; set; }
        public virtual Bank Bank { get; set; }
        public bool IsActive { get; set; } = true;
    }
}

FinTech/ViewModels/PaymentAccounts/ChartsPaymentAccountViewModel.cs
namespace FinTech.ViewModels.PaymentAccounts
{
    public class ChartsPaymentAccountViewModel
    {
        public string Name { get; set; }
        public decimal[] SumPerMonths { get; set; }
    }
}

FinTech/ViewModels/PaymentAccounts/CreatePaymentAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FinTech.Enums;
using FinTech.ViewModels.Banks;
using Microsoft.AspNetCore.Mvc;

namespace FinTech.ViewModels.PaymentAccounts
{
    public class CreatePaymentAccountViewModel
    {
        [Required(ErrorMessage = "Введите номер расчетного счета")]
        [MinLength(20, ErrorMessage = "Введите 20-тизначный буквенно-цифровой код")]
        [MaxLength(20, ErrorMessage = "Введите 20-тизначный буквенно-цифровой код")]
        [Remote("ValidateBankNameAndIban", "PaymentAccountValidation", 
            AdditionalFields = "Iban,BankName,CompanyId", ErrorMessage = "Такой счет уже есть")]
        public string Iban { get; set; }
        public string BankId { get; set; }
        [Required(ErrorMessage = "Введите сумму на рассчетном счете")]
        public decimal Amount { get; set; }
        public CurrencyTypes CurrencyType { get; set; }
        public DateTime CreationDate { get; set; }
        public string CompanyId { get; set; }
        public string CounterpartyId { get; set; }
        public List<BankViewModel> Banks { get; set; }

        public override string ToString()
        {
            return $"Amount:{Amount},Banks:{Banks},Iban:{Iban},BankId:{BankId} CompanyId:{CompanyId}," +
                   $"ConterpartyId:{CounterpartyId}, Date:{CreationDate}, Type:{CurrencyType}";
        }
    }
}

FinTech/ViewModels/PaymentAccounts/PaymentAccountViewModel.cs
using System;
using FinTech.Enums;
using FinTech.ViewModels.Banks;
using FinTech.ViewModels.Companies;
using FinTech.ViewModels.Counterparties;

namespace FinTech.ViewModels.PaymentAccounts
{
    public class PaymentAccountViewModel
    {
        public string Id { get; set; }
        public string Iban { get; set; }
        public BankViewModel Bank { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public CurrencyTypes CurrencyType { get; set; }
        public DateTime CreationDate { get; set; }
        public CompanyViewModel Company { get; set; }
        public CounterpartyViewModel Counterparty { get; set; }
    }
}

FinTech/ViewModels/PaymentAccounts/UpdatePaymentAccountViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using FinTech.Enums;
using FinTech.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinTech.ViewModels.PaymentAccounts
{
    public class UpdatePaymentAccountViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage = "Введите номер расчетного счета")]
        [MinLength(20, ErrorMessage = "Введите 20-тизначный буквенно-цифровой код")]
        [MaxLength(20, ErrorMessage = "Введите 20-тизначный буквенно-цифровой код")]
        [Remote("ValidateBankNameAndIban", "PaymentAccountValidation", 
            AdditionalFields = "Iban,BankName", ErrorMessage = "Такой счет уже есть")]
        public string Iban { get; set; }
        public string BankId { get; set; }
        public decimal Amount { get; set; }
        public CurrencyTypes CurrencyType { get; set; }
        public DateTime CreationDate { get; set; }
        public string CompanyId { get; set; }
        public string CounterpartyId { get; set; }
        
        
        public PaymentAccount ConvertToPaymentAccount()
        {
            return new PaymentAccount()
            {
                Id = Id,
                Amount = Amount,
                Iban = Iban,
                BankId = BankId,
                CompanyId = CompanyId,
                CounterpartyId = CounterpartyId,
                CurrencyType = CurrencyType
            };
        }

        public override string ToString()
        {
            return $"Amount:{Amount},Id:{Id},Iban:{Iban},BankId:{BankId}," +
            $"CompanyId:{CompanyId}, ConterpartyId:{CounterpartyId}, Date:{CreationDate}, Type:{CurrencyType}";
        }
    }
}

FinTech/Controllers/PaymentAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinTech.Enums;
using FinTech.Models;
using FinTech.Services.BankService;
using FinTech.Services.CompanyService;
using FinTech.Services.PaymentAccountService;
using FinTech.ViewModels.PaymentAccounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace FinTech.Controllers
{
    [Authorize]
    public class PaymentAccountController : Controller
    {
        private readonly IPaymentAccountService _paymentAccountService;
        private readonly ICompanyService _companyService;
        private readonly IBankService _bankService;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private static readonly Logger Logger = LogManager.GetLogger("PaymentAccountLogger");

        public PaymentAccountController(
            IPaymentAccountService paymentAccountService,
            ICompanyService companyService,
            IBankService bankService,
            IMapper mapper, UserManager<User> userManager)
        {
            _paymentAccountService = paymentAccountService;
            _companyService = companyService;
            _bankService = bankService;
            _mapper = mapper;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var company = _companyService.GetCompanyFromUser(user);
                ViewBag.Company = company;
                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Index:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public IActionResult GetPaymentAccounts(string companyId)
        {
            try
            {
                var paymentAccountViewModels = _paymentAccountService.GetAccountsByCompanyId(companyId)
                    .Where(pa => pa.IsActive)
                    .ToList();
                return PartialView("~/Views/PartialViews/PaymentAccount/_ReturnPaymentAccounts.cshtml",
                    paymentAccountViewModels);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetPaymentAccounts:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public IActionResult ShowDetails(string accountId)
        {
            try
            {
                if (_paymentAccountService.CheckExistById(accountId))
                {
                    var viewModel = _paymentAccountService.GetAccountInfoByAccountId(accountId);
                    return View(viewModel);
                }

                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе ShowDetails:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public IActionResult Create(string companyId, string redirectAction)
        {
            try
            {
                var model = new CreatePaymentAccountViewModel
                {
                    CompanyId = companyId,
                    CurrencyType = CurrencyTypes.KZT,
                    CreationDate = DateTime.Now,
                    Banks = _bankService.GetBankViewModels()
                };
                return View(model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Create:\n {e}");
                return BadRequest(400);
            }
        }


        [HttpPost]
        public IActionResult Create(CreatePaymentAccountViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные в методе Create:\n {model}");
                if (ModelState.IsValid)
                {
                    _paymentAccountService.Create(model);
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Create:\n {e}");
                return BadRequest(400);
            }

            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult Edit(string id, string redirectAction)
        {
            try
            {
                if (_paymentAccountService.CheckExistById(id))
                {
                    var paymentAccount = _paymentAccountService.GetById(id);
                    var model = _mapper.Map<UpdatePaymentAccountViewModel>(paymentAccount);
                    return View(model);
                }

                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Edit:\n {e}");
                return NotFound();
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "root, admin")]
        public IActionResult Edit(UpdatePaymentAccountViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные в методе Create:\n {model}" );
                if (_paymentAccountService.CheckExistById(model.Id))
                {
                    _paymentAccountService.Update(model);
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }

                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Edit:\n {e}");
                return BadRequest(400);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "root, admin")]
        public IActionResult Delete(string id)
        {
            try
            {
                if (_paymentAccountService.CheckExistById(id))
                {
                    _paymentAccountService.DeactivateById(id);
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }

                return NotFound("Расчетный счет не найден");

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Delete:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetCompanyPaymentAccounts()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var company = _companyService.GetCompanyFromUser(user);
                List<PaymentAccountViewModel> model = _paymentAccountService.GetAccountsByCompanyId(company.Id);
                return PartialView("~/Views/PartialViews/PaymentAccount/_AccountBalancePartialView.cshtml", model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе Index:\n {e}");
                return null;
            }
        }
    }
}

FinTech/Views/PartialViews/PaymentAccount/_AccountBalancePartialView.cshtml
@using FinTech.ViewModels.PaymentAccounts
@model List<FinTech.ViewModels.PaymentAccounts.PaymentAccountViewModel>

@{
    PaymentAccountViewModel firstPaymentAccount = null;
    if (Model.Count != 0)
    {
        firstPaymentAccount = Model.First(p => p.IsActive);
    }
}

@if (Model.Count != 0)
{
    <div class="btn-group">
        <div class="payment-account-card" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <p class="small" id="default-iban" default-value="Счет: @firstPaymentAccount.Iban"></p>
            <h6 class="payment-account-card-amount" id="default-amount" default-value="@firstPaymentAccount.Amount @firstPaymentAccount.CurrencyType"></h6>
        </div>
        <div class="dropdown-menu payment-account-dropdown-menu">
            @foreach (var paymentAccount in Model)
            {
                if (paymentAccount.IsActive)
                {
                    <li>
                        <div class="payment-account-card account" id="@paymentAccount.Id">
                            <p class="small iban" id="iban-@paymentAccount.Id">Счет: @paymentAccount.Iban</p>
                            <h6 class="amount" id="amount-@paymentAccount.Id">
                                @paymentAccount.Amount @paymentAccount.CurrencyType
                            </h6>
                        </div>
                    </li>
                }
            }
        </div>
    </div>
}

FinTech/Views/PartialViews/PaymentAccount/_ReturnPaymentAccounts.cshtml
@model List<FinTech.ViewModels.PaymentAccounts.PaymentAccountViewModel>

@if (Model.Count == 0)
{
    <h2 class="mt-3 text-align-center">Список платежных счетов пуст</h2>
}
else
{
    <table class="table mt-3">
      <thead>
        <tr>
            <th scope="col">IBAN</th>
            <th scope="col">Имя банка</th>
            <th scope="col">Баланс</th>
            <th scope="col">Код валюты</th>
            <th scope="col">Имя компании</th>
            <th scope="col">Имя контрагента</th>  
            <th scope="col">Действия</th>  
        </tr>
      </thead>
      <tbody>
      @foreach (var paymentAccount in Model)
      {
          <tr>
              <td>@paymentAccount.Iban</td>
              <td>@paymentAccount.Bank.Name</td>
              <td>@paymentAccount.Amount</td>
              <td>@paymentAccount.CurrencyType.ToString()</td>
              <td>@paymentAccount.Company.Name</td>
              @if (paymentAccount.Counterparty != null)
              {
                  <td>@paymentAccount.Counterparty.Name</td>
              }
              else
              {
                  <td></td>
              }
              <td>
                  <a class="text-decoration-none m-2" asp-action="ShowDetails" asp-controller="PaymentAccount" asp-route-accountId="@paymentAccount.Id">Детали</a>
                  <a class="text-decoration-none m-2" asp-action="Edit" asp-controller="PaymentAccount" asp-route-id="@paymentAccount.Id" asp-route-redirectAction="@Url.Action("Index", "PaymentAccount")">Редактировать</a>
                  <a class="text-decoration-none m-2 deletePaymentAccountButton" payment-account-id="@paymentAccount.Id" href="#">Удалить</a>
              </td>
          </tr>
      }
      </tbody>
    </table>
}