FinTech/Models/BudgetItem.cs
using FinTech.Enums;

namespace FinTech.Models
{
    public class BudgetItem
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public BudgetItemTypes Type { get; set; }
        public virtual Company Company { get; set; }
        public virtual AssetLiability AssetLiability { get; set; }
        public bool IsActive { get; set; } = true;
    }
}

FinTech/ViewModels/BudgetItems/BudgetItemViewModel.cs
using FinTech.Enums;
using FinTech.ViewModels.AssetLiabilities;
using FinTech.ViewModels.Companies;

namespace FinTech.ViewModels.BudgetItems
{
    public class BudgetItemViewModel
    {
        public string Id { get; set;}
        public string Name { get; set; }
        
        public string Article { get; set; }
        public BudgetItemTypes Type { get; set; }
        public string AssetLiabilityId { get; set; }
        public AssetLiabilityViewModel AssetLiability { get; set; }
        public bool IsActive { get; set; } = true;
        public CompanyViewModel Company { get; set; }
        public string BudgetTypeId { get; set; }
    }
}

FinTech/ViewModels/BudgetItems/ChartsBudgetItemViewModel.cs
using System.Collections.Generic;

namespace FinTech.ViewModels.BudgetItems
{
    public class ChartsBudgetItemViewModel
    {
        public string Name { get; set; }
        public List<decimal> SumPerMonths { get; set; }
        public decimal TotalSum { get; set; }
    }
}

FinTech/ViewModels/BudgetItems/CreateBudgetItemViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FinTech.Enums;
using FinTech.ViewModels.AssetLiabilities;
using Microsoft.AspNetCore.Mvc;

namespace FinTech.ViewModels.BudgetItems
{
    public class CreateBudgetItemViewModel
    {
        public string Id { get; set;}
        
        [Remote("ValidateBudgetItem", "BudgetItemValidationController")]
        [Required(ErrorMessage = "Введите название статьи")]
        public string Name { get; set; }
        public string? AssetLiabilityId { get; set; }
        public BudgetItemTypes Type { get; set; }
        public bool IsActive { get; set; } = true;
        public string CompanyBin { get; set; }
        public List<AssetLiabilityViewModel> Assets { get; set; }
        public List<AssetLiabilityViewModel> Liabilities { get; set; }

        public override string ToString()
        {
            return $"Id: {Id}, Assets: {Assets}, " +
                   $"Name: {Name}, Type: {Type}, CompanyBin: {CompanyBin}, IsActive: {IsActive}, " +
                   $"AssetLiabilityId: {AssetLiabilityId}";
        }
    }
}

FinTech/ViewModels/BudgetItems/UpdateBudgetItemViewModel.cs
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using FinTech.Enums;
using FinTech.Models;
using FinTech.ViewModels.AssetLiabilities;
using FinTech.ViewModels.Companies;
using Microsoft.AspNetCore.Mvc;

namespace FinTech.ViewModels.BudgetItems
{
    public class UpdateBudgetItemViewModel
    {
        public string Id { get; set;}
        
        [Remote("ValidateBudgetItem", "BudgetItemValidationController", ErrorMessage = "Статья уже занята")]
        [Required(ErrorMessage = "Введите название статьи")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Выберите тип статьи: доход или расход")]
        public BudgetItemTypes Type { get; set; }
        public string? AssetLiabilityId { get; set; }
        public AssetLiabilityViewModel AssetLiability { get; set; }
        public string CompanyBin { get; set; }
        public string CompanyId { get; set; }
        public CompanyViewModel Company { get; set; }
        public bool IsActive { get; set; } = true;
        
        public BudgetItem ConvertToBudgetItem(IMapper mapper)
        {
            return new BudgetItem()
            {
                Id = Id,
                Name = Name,
                AssetLiability = mapper.Map<AssetLiability>(AssetLiability),
                Company = mapper.Map<Company>(Company),
                Type = Type
            };
        }

        public override string ToString()
        {
            return $"Company: {Company}, Id: {Id}, " +
                   $"Name: {Name}, Type: {Type}, AssetLiability: {AssetLiability}, " +
                   $"CompanyBin: {CompanyBin}, CompanyId: {CompanyId},  IsActive: {IsActive}, " +
                   $"AssetLiabilityId:{AssetLiabilityId}";
        }
    }
}

FinTech/Controllers/AssetLiabilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinTech.Models;
using FinTech.Services.AssetLiabilityService;
using FinTech.Services.CompanyService;
using FinTech.ViewModels.AssetLiabilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace FinTech.Controllers
{
    [Authorize]
    public class AssetLiabilityController : Controller
    {
        private readonly IAssetLiabilityService _assetLiabilityService;
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private static readonly Logger Logger = LogManager.GetLogger("AssetLiabilityLogger");

        public AssetLiabilityController(
            IAssetLiabilityService assetLiabilityService,
            ICompanyService companyService, 
            IMapper mapper, 
            UserManager<User> userManager)
        {
            _assetLiabilityService = assetLiabilityService;
            _companyService = companyService;
            _mapper = mapper;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult GetFormAssetLiability(string assetLiability)
        {
            try
            {
                CreateAssetLiabilityViewModel model = new CreateAssetLiabilityViewModel();
                if (assetLiability == "Asset")
                    return PartialView("~/Views/PartialViews/AssetLiability/_AssetPartialView.cshtml", model);
                if (assetLiability == "Liability")
                    return PartialView("~/Views/PartialViews/AssetLiability/_LiabilityPartialView.cshtml", model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetFormAssetLiability:\n {e}");
                return BadRequest(400);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAssetLiability(CreateAssetLiabilityViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные CreateAssetLiability\n {model}");
                var user = await _userManager.GetUserAsync(User);
                model.CompanyId = user.Company.Id;
                
                if(ModelState.IsValid)
                {
                    _assetLiabilityService.CreateAssetLiability(model);
                }
                else
                {
                    foreach (var modelState in ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            Console.WriteLine(error.ErrorMessage);
                        }
                    }
                }
                ModelState.Clear();
                return View("/Views/BudgetItem/CreateBudgetItem.cshtml");
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CreateAssetLiability:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult EditAssetLiability(string id)
        {
            try
            {
                if (_assetLiabilityService.CheckExist(id))
                {
                    AssetLiability assetLiability = _assetLiabilityService.GetAssetLiabilityById(id);
                    var assetLiabilityViewModel = _mapper.Map<AssetLiabilityViewModel>(assetLiability);
                    return View(assetLiabilityViewModel);
                }
                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе EditAssetLiability:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpPost]
        [Authorize(Roles = "root, admin")]
        public async Task<IActionResult> EditAssetLiability(AssetLiabilityViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные EditAssetLiability:\n {model}");
                var user = await _userManager.GetUserAsync(User);
                model.CompanyId = user.Company.Id;
                if (_assetLiabilityService.CheckExist(model.Id))
                {
                    _assetLiabilityService.UpdateAssetLiability(model);
                    return RedirectToAction("GetListAssetLiability");
                }
                ModelState.Clear();
                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе EditAssetLiability:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult DeactivateAssetLiability(string id)
        {
            try
            {
                if (_assetLiabilityService.CheckExist(id))
                {
                    _assetLiabilityService.DeactivateAssetLiability(id);
                    return RedirectToAction("GetListAssetLiability");
                }

                return NotFound("Статья не найдена");
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе DeleteAssetLiability:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetListAssetLiability()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var testCompanyId = _companyService.GetCompanyFromUser(user).Id;
                var assetLiabilities = _assetLiabilityService.GetAssetLiabilitiesByCompanyId(testCompanyId);
                return View(_mapper.Map<List<AssetLiabilityViewModel>>(assetLiabilities.ToList()));
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetListAssetLiability:\n {e}");
                return BadRequest(400);
            }
        }
    }
}

FinTech/Controllers/BudgetItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinTech.Enums;
using FinTech.Models;
using FinTech.Services.AssetLiabilityService;
using FinTech.Services.BudgetItemService;
using FinTech.ViewModels.AssetLiabilities;
using FinTech.ViewModels.BudgetItems;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NLog;

namespace FinTech.Controllers
{
    [Authorize]
    public class BudgetItemController : Controller
    {
        private readonly IBudgetItemService _budgetItemService;
        private readonly IMapper _mapper;
        private readonly IAssetLiabilityService _assetLiabilityService;
        private readonly UserManager<User> _userManager;
        private static readonly Logger Logger = LogManager.GetLogger("BudgetItemLogger");

        public BudgetItemController(
            IBudgetItemService budgetItemService, 
            IMapper mapper, 
            IAssetLiabilityService assetLiabilityService,
            UserManager<User> userManager)
        {
            _budgetItemService = budgetItemService;
            _mapper = mapper;
            _userManager = userManager;
            _assetLiabilityService = assetLiabilityService;
        }

        [HttpGet]
        public IActionResult CreateBudgetItem()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetFormBudgetItem(string budgetType)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var companyId = user.Company.Id;
                var assets = _assetLiabilityService.GetAssetLiabilitiesByCompanyIdAndType(companyId, AssetLiabilityTypes.Asset);
                var liabilities = _assetLiabilityService.GetAssetLiabilitiesByCompanyIdAndType(companyId, AssetLiabilityTypes.Liability);
                CreateBudgetItemViewModel model = new CreateBudgetItemViewModel()
                {
                    Assets = _mapper.Map<List<AssetLiabilityViewModel>>(assets.ToList()),
                    Liabilities = _mapper.Map<List<AssetLiabilityViewModel>>(liabilities.ToList()),
                    CompanyBin = user.Company.Bin
                };
                Logger.Info($"Входные данные GetFormBudgetItem\n {model}");
                if (budgetType == "Income")
                    return PartialView("~/Views/PartialViews/BudgetItem/_BudgetItemIncome.cshtml", model);
                if (budgetType == "Expense")
                    return PartialView("~/Views/PartialViews/BudgetItem/_BudgetItemExpense.cshtml", model);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetFormBudgetItem:\n {e}");
                return BadRequest(400);
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult CreateBudgetItem(CreateBudgetItemViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные GetFormBudgetItem\n {model}");
                if (ModelState.IsValid)
                    _budgetItemService.CreateBudgetItem(model);
                ModelState.Clear();
                return View();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CreateBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult EditBudgetItem(string id)
        {
            try
            {
                if (_budgetItemService.CheckExistById(id))
                {
                    var budgetItem = _budgetItemService.GetBudgetItemById(id);
                    var model = _mapper.Map<BudgetItemViewModel>(budgetItem);
                    return View(model);
                }
                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе CreateBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpPost]
        [Authorize(Roles = "root, admin")]
        public async Task<IActionResult> EditBudgetItem(UpdateBudgetItemViewModel model)
        {
            try
            {
                Logger.Info($"Входные данные в методе EditBudgetItem:\n {model}");
                if (_budgetItemService.CheckExistById(model.Id))
                {
                    var user = await _userManager.GetUserAsync(User);
                    model.CompanyId = user.Company.Id;
                    _budgetItemService.UpdateBudgetItem(model);
                    return RedirectToAction("GetBudgetIemList");
                }
                ModelState.Clear();
                return View();

            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе EditBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        [Authorize(Roles = "root, admin")]
        public IActionResult DeleteBudgetItem(string id)
        {
            try
            {
                if (_budgetItemService.CheckExistById(id))
                {
                    _budgetItemService.DeleteBudgetItemById(id);
                    return RedirectToAction("GetBudgetIemList"); 
                }

                return NotFound();
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе DeleteBudgetItem:\n {e}");
                return BadRequest(400);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetBudgetIemList()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var testCompanyId = user.Company.Id;
                var budgetItems = _budgetItemService.GetBudgetItemsListByCompanyId(testCompanyId, null);
                var budgetItemsList = _mapper.Map<List<BudgetItemViewModel>>(budgetItems.ToList());
                return View(budgetItemsList);
            }
            catch (Exception e)
            {
                Logger.Error($"Произошла ошибка в методе GetBudgetIemList:\n {e}");
                return BadRequest(400);
            }
        }
    }
}

FinTech/Views/BudgetItem/CreateBudgetItem.cshtml
@model dynamic

@{
    ViewBag.Title = "Создание учетной статьи";
    Layout = "_Layout";
}

<h1 class="text-align-center mt-5">@ViewBag.Title</h1>


<div class="tab mt-5">
    <a  class="btn btn-light budget_btn" data-type="Income">Доходы</a>
    <a class="btn btn-light budget_btn" data-type="Expense" >Расходы</a>
    <a class="btn btn-light assetLiability_btn" data-type="Asset">Активы</a>
    <a class="btn btn-light assetLiability_btn" data-type="Liability" >Обязательства</a>
</div>

<div class="form">
    <div asp-validation-summary="All"></div>
</div>

@section Scripts
{
    <script>
       $(".budget_btn").click(function (){
                          let budgetType = $(this).attr("data-type");                      
                           $.ajax({
                           url : '@Url.Action("GetFormBudgetItem", "BudgetItem")',
                           type : 'GET',
                           data : {
                           'budgetType' : budgetType
                           },
                           success: function (data){
                           $('.form').html(data);
                              }
                             });
                       });
       $(".assetLiability_btn").click(function (){
                                 let AssetLiability = $(this).attr("data-type");                      
                                  $.ajax({
                                  url : '@Url.Action("GetFormAssetLiability", "AssetLiability")',
                                  type : 'GET',
                                  data : {
                                  'AssetLiability' : AssetLiability
                                  },
                                  success: function (data){
                                  $('.form').html(data);
                                     }
                                    });
                              });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FinTech/Views/BudgetItem/EditBudgetItem.cshtml
@using FinTech.Enums
@model FinTech.ViewModels.BudgetItems.BudgetItemViewModel

@{
    ViewBag.Title = "Изменение статьи";
    Layout = "_Layout";
}

@{
    if (Model != null)
    {
        <h1 class="text-align-center mt-5">Изменение статьи</h1>

        <div class="row d-flex justify-content-center mt-5">
            <form asp-controller="BudgetItem" asp-action="EditBudgetItem" method="post">
                <input class="form-control m-1" asp-for="Name" placeholder="Название статьи расхода"/>
                <span asp-validation-for="Name"></span>
                @if (Model.Type != BudgetItemTypes.Income)
                {
                    <div class="form_row">
                        <label class="w-100">
                            Статья расхода <br>
                            <select asp-for="Type" id="" class="form-control">
                                <option value="@BudgetItemTypes.Permanent">@EnumHelper.GetDescription(BudgetItemTypes.Permanent)</option>
                                <option value="@BudgetItemTypes.Variable">@EnumHelper.GetDescription(BudgetItemTypes.Variable)</option>
                            </select>
                        </label>
                    </div>
                }
                <input hidden asp-for="Type" value="@Model.Type"/>
                <input hidden asp-for="Id" value="@Model.Id"/>
                <span asp-validation-for="Type"></span>
                <button type="submit" class="btn-primary btn w-100 text-center">Изменить</button>
            </form>
        </div>
    }
    else
    {
        <h2 class="text-center">Статья не найдена или была удалена</h2>
    }
}

FinTech/Views/BudgetItem/GetBudgetIemList.cshtml
@using FinTech.Enums
@model System.Collections.Generic.List<FinTech.ViewModels.BudgetItems.BudgetItemViewModel>

@{
    ViewBag.Title = "Список доходов и расходов";
    Layout = "_Layout";
}
<a class="btn-primary btn mt-5" asp-controller="BudgetItem" asp-action="CreateBudgetItem">Назад</a>
@if (Model.Count > 0)
{
    <table class="table mt-5">
        <tr>
            <th class="text-center">Название</th>
            <th class="text-center">Тип статьи</th>
            @if (User.IsInRole("root") || User.IsInRole("admin"))
            {
                <th class="text-center">Действие</th> 
            }
        </tr>
        @foreach (var article in Model)
        {
            <tr>
                <td class="text-center" article-id="@article.Id">
                    @article.Name
                </td>
                <td class="text-center">
                    @if (article.Type == BudgetItemTypes.Income)
                    {
                        <p>Доход</p>
                    }
                    else
                    {
                        <p>@EnumHelper.GetDescription(article.Type)</p>
                    }
                </td>
                <td class="text-center">
                    @if (User.IsInRole("root") || User.IsInRole("admin"))
                    {
                        <a class="btn btn-outline-primary change" asp-action="EditBudgetItem"
                           asp-route-id="@article.Id">Изменить</a>
                        <a class="btn btn-outline-danger delete" id="@article.Id" data-name="@article.Name">Удалить</a>
                    }
                </td>
            </tr>
        }
    </table>
}
else
{
    <h4 class="text-center">Список учетных статей пуст</h4>
}

@section Scripts
{
    <script>
        $(document).ready(function (){
            $(".delete").click(function (){
                let id = $(this).attr("id");
                let name = $(this).attr("data-name")
                let deleteConfirm = confirm(`Удалить статью ${name}?`)
                if (deleteConfirm){
                    $.get(`@Url.Action("DeleteBudgetItem", "BudgetItem")?id=${id}`, function (){
                        location.reload()
                    })
                }
            })
        })
    </script>
}